Adding a json file for the yml file in workflow-templates
pyPadaiyal/.github pull request #7
Opened 2021-12-09 01:59 UTC by aikido-sensei

Fixes #4

## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **setup.py version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **setup.py version is set to the latest date** If not, explain why.

2021-12-09 02:04 UTC, the-c0d3br34k3r commented on workflow-templates/python_build.json
> +	"Python POM"
```suggestion
```

2021-12-09 02:04 UTC, the-c0d3br34k3r commented on workflow-templates/combined_OS.yml
> +name: Python build
```suggestion
name: Python build - tests flake8
```

2021-12-09 02:04 UTC, silvs110 requested changes

2021-12-09 02:04 UTC, silvs110 commented on workflow-templates/python_build.json
> +	"Python POM"
Remove Python POM

2021-12-09 02:04 UTC, the-c0d3br34k3r requested changes
Squash all commits please.

2021-12-09 02:04 UTC, aikido-sensei commented on workflow-templates/python_build.json
> +	"Python POM"
Done!

2021-12-11 01:57 UTC, aikido-sensei commented on workflow-templates/python_build.json
> +	"Python POM"
Fixed!

2021-12-11 01:57 UTC, aikido-sensei commented
> Squash all commits please.

Done!

2021-12-11 01:58 UTC, the-c0d3br34k3r approved these changes

2021-12-11 01:59 UTC, silvs110 approved these changes

2021-12-15 01:05 UTC, merged